services:
  db:
    image: mongo:6-jammy
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env
  redis:
    image: bitnami/redis:latest
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  bot:
    build: 
      context: .
    command: ["uv", "run", "python", "-m", "bot"]
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
volumes:
  mongodb-data:
  redis:
  redis-config: