name: Release
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-22.04-arm
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/sqlmerr/tasklistbot:${{github.ref_name}}
            ghcr.io/sqlmerr/tasklistbot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
